name: exportable
version: 0.1.0
description: Provides an ability to export/import simple objects.
author: Alexander Tkachev <alex.leksat@gmail.com>
homepage: http://github.com/Leksat/dart-exportable

dev_dependencies:
  unittest: 'any'
  test_toolkit: '>=0.5.0'
  junitconfiguration: ">=1.0.0 <2.0.0"
